### ISSUE TITLE
Ajout d'une partie

### ISSUE THREAD

**Issue by FinetClement** [thecheatmine/TP3#19]
Il faudrait ajouter une partie Valentin !

**Comment by thecheatmine** [comment]
Il me faut un cahier des charges, ou au moins + de précisions

**Comment by FinetClement** [comment]
Un cahier des charges, régulièrement appelé CDC est un document (PDF, Word..) qui permet d’expliquer toutes les spécificités, les attentes et les contraintes d’un projet aux freelances ou aux agences. En d’autres termes, un cahier des charges est un élément essentiel de la conception d’un projet web. Par exemple le cahier des charges pour un site internet va établir une description fonctionnelle des différents éléments pour que les différentes parties prenantes du projet soit sur la même longueur d’ondes. (Pour approfondir : Comment faire un cahier des charges)

**Comment by TeoTjamp** [comment]
J'aime les pommes
