### ISSUE TITLE
J'ai remarqué un problème dans le code

### ISSUE THREAD

**Issue by RouzeLilian** [thecheatmine/TP3#22]
Je pense que le bleu de fond de cases n'est pas très design, il faudrait le changer.

**Comment by thecheatmine** [comment]
Il me faut plus de précisions

**Comment by PierruDimitry** [comment]
Quelle couleur

**Comment by TeoTjamp** [comment]
Moi aussi j'ai remarqué un gros probleme

**Comment by RouzeLilian** [comment]
Tu peux choisir la couleur, sinon un rouge carrosserie me va bien.

**Comment by RouzeLilian** [comment]
Et Téo, tu peux parler sur le dos des gens, je t'entendrais toujours ! Et non moi PERSONNELLEMENT je ne TROLL PAS !

**Comment by thecheatmine** [comment]
tais toi

**Comment by RouzeLilian** [comment]
dwghf
