### ISSUE TITLE
Changement du fond

### ISSUE THREAD

**Issue by FinetClement** [thecheatmine/TP3#24]
Je pense que le fond n'est pas vraiment approprié pour notre thème.

**Comment by GodderidgeAurore** [comment]
J'étais sur le point de l'écrire

**Comment by thecheatmine** [comment]
Propose moi donc un meilleur fond et celui-ci sera mis en place

**Comment by FinetClement** [comment]
https://wall.alphacoders.com/big.php?i=813087&lang=French

**Comment by thecheatmine** [comment]
Votre requête a été prise en compte, cependant pour que celle-ci continue d'être notre priorité, veuillez faire un don de 1000€ à Supinfo

**Comment by thecheatmine** [comment]
maintenant stop
