### ISSUE TITLE
Probléme au niveau du CSS

### ISSUE THREAD

**Issue by PierruDimitry** [thecheatmine/TP3#30]
J'ai remarquer un probléme dans le CSS a la ligne 34. mon decteteur de probléme la vue et je pense que c'est pas trés serieux de laisser une aussi grosse erreur.
Une balise <p> ne se mais pas dans le CSS

**Comment by thecheatmine** [comment]
Bonjour, je ne trouve pas l'erreur en question à la ligne 34

**Comment by TeoTjamp** [comment]
regarde mieux

**Comment by PierruDimitry** [comment]
A la fin de la balise <p> regarde au debut dfe la balise <b>

**Comment by thecheatmine** [comment]
Ceci est la ligne 34 : 	background: #333;
